app_id="xyz.toastxc.Kuma"
app_name="Kuma"
profile="release"
bin="gui"
permissions = [
    # network
    "--share=network",
    # display
    "--socket=wayland",
    "--socket=fallback-x11",
    # OpenGL: needed for EGUI
    "--device=dri",
    # notifications
    "--socket=session-bus",
]

[desktopfile]
terminal= false


