app_id="xyz.toastxc.Kuma"
app_name="Kuma"
profile="release"
bin="gui"
permissions = [
    # network
    "--share=network",
    # display
    "--socket=x11",
    "--socket=wayland",
    "--socket=fallback-x11",
    # OpenGL
    "--device=dri",
    # notifications
    "--socket=session-bus",
]

[desktopfile]
terminal= false


